### ISSUE TITLE
ID for getWorkspaces?

### ISSUE THREAD

**Issue by dlasky** [joshuarubin/go-sway#1]
looks like your struct has `Num` but not `ID` which makes focus referencing more fragile.

1 liner but more than happy to PR

**Comment by joshuarubin** [comment]
Which struct are you talking about? There are several structs which do have ID and as I remember those without it had a good reason not to. I might be wrong though and am happy to look into it.

**Comment by dlasky** [comment]
Hey, thanks for getting back to me. This was the struct in question: https://github.com/joshuarubin/go-sway/blob/master/types.go#L121

Basically if someone is using something like swayest https://old.reddit.com/r/swaywm/comments/ml66z5/swayest_workstyle/

the actual workspace names can be changed dynamically during runtime, and I'm using this for building out a bar where i want 'stable' ids exposed for tracking the workspaces.

I've updated it on my fork, if you want me to PR, lmk!

**Comment by joshuarubin** [comment]
well whadayaknow, it certainly is returned. I updated the struct and tagged a new version. Thanks for letting me know!

**Comment by dlasky** [comment]
Closed with 9562910f80b322914ffcf1437178def02cce6eef

No problem thanks for maintaining this and the fast response. I'll delete my fork as well.
